/* 
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
*/

char findTheDifference(char* s, char* t) {
    int sSize = strlen(s);
    int tSize = strlen(t);
    int sSum = 0;
    int tSum = 0;
    char new = ' ';
    for (int i = 0; i < tSize; i++) {
        tSum += (int)t[i];
    }
    for (int j = 0; j < sSize; j++) {
        sSum += (int)s[j];
    }
    new = (char)(tSum - sSum);
    return new;
}